"""Tier 1 States (Ranks 1-4): California, Texas, New York, Florida."""

TIER1_DATA = {
    "CA": {
        "state_code": "CA",
        "state_name": "California",
        "gdp_billions": 3890,
        "rank": 1,
        "regulatory_body": "California Public Utilities Commission (CPUC) / California Energy Commission (CEC)",
        "utilities": [
            {
                "name": "Pacific Gas and Electric",
                "short_name": "PG&E",
                "org_type": "utility",
                "sub_type": "Investor-Owned Utility (IOU)",
                "parent_holding_company": "PG&E Corporation",
                "website": "https://www.pge.com",
                "domain": "pge.com",
                "city": "Oakland",
                "state": "CA",
                "zip_code": "94612",
                "service_territory": "Northern & Central California (San Francisco, Silicon Valley, Central Valley)",
                "description": "One of the largest combined natural gas and electric energy companies in the United States, serving 16 million people across 70,000 square miles in Northern and Central California.",
                "logo_domain": "pge.com",
                "founded_year": 1905,
                "programs": [
                    {
                        "name": "PG&E EPIC Innovation & Technology Transfer",
                        "program_type": "innovation",
                        "description": "Electric Program Investment Charge (EPIC) research, demonstration, and technology deployment for wildfire safety, grid resilience, and clean energy integration.",
                        "url": "https://www.pge.com/epic",
                        "active": True,
                        "target_stage": "demonstration",
                    },
                    {
                        "name": "PG&E Distribution Investment Deferral & NWA",
                        "program_type": "deployment",
                        "description": "Non-Wires Alternatives (NWA) and Distributed Investment Deferral Framework (DIDF) solicitations to resolve localized grid capacity constraints.",
                        "url": "https://www.pge.com/b2b/energy-procurement/distribution-deferral.page",
                        "active": True,
                        "target_stage": "scale-up",
                    },
                    {
                        "name": "PG&E Clean Hydrogen & Long-Duration Storage RFO",
                        "program_type": "innovation",
                        "description": "Procurement of multi-day and multi-hour long-duration energy storage (LDES) and green hydrogen generation pilots.",
                        "url": "https://www.pge.com/rfo",
                        "active": True,
                        "target_stage": "growth",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "PGE-EPIC4-2026",
                        "name": "PG&E EPIC 4 Innovation & Grid Modernization Demonstrations",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "grant",
                        "total_funding": 62500000.0,
                        "max_per_award": 5000000.0,
                        "cost_share_pct": 20.0,
                        "short_description": "Competitive solicitation for grid-forming inverters, advanced wildfire detection AI sensors, and long-duration storage demonstration pilots on the PG&E electric grid.",
                        "service_territory": "Northern and Central California",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.pge.com/epic",
                        "year": 2026,
                        "keywords": "EPIC, wildfire sensors, grid-forming inverters, long-duration storage, microgrid, resilience",
                        "technologies": ["Grid Modernization & Smart Grid", "Energy Storage", "AI, Computing & Energy Cyber", "Microgrids & Resilience"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Electricity", "Storage & Chemical"],
                        "stage": "Pilot & Demonstration",
                    },
                    {
                        "solicitation_number": "PGE-DIDF-2026",
                        "name": "PG&E Distribution Investment Deferral (NWA) Solicitation",
                        "solicitation_type": "RFO",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 45000000.0,
                        "max_per_award": 15000000.0,
                        "short_description": "Procurement of third-party distributed energy resources (DERs), front-of-meter battery storage, and dynamic load management to defer traditional substation capital upgrades.",
                        "service_territory": "Central Valley, Bay Area & North Coast",
                        "utility_program_type": "NWA",
                        "procurement_portal_url": "https://www.pge.com/b2b/energy-procurement/distribution-deferral.page",
                        "year": 2026,
                        "keywords": "NWA, distribution deferral, battery storage, demand response, DERMS",
                        "technologies": ["Non-Wires Solutions (NWS)", "Energy Storage", "Solar PV"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Electricity", "Storage & Chemical"],
                        "stage": "Deployment & Infrastructure",
                    },
                    {
                        "solicitation_number": "PGE-LDES-2025",
                        "name": "PG&E Multi-Day Long-Duration Energy Storage Pilot RFO",
                        "solicitation_type": "RFO",
                        "status": "closed",
                        "funding_type": "contract",
                        "total_funding": 80000000.0,
                        "max_per_award": 40000000.0,
                        "short_description": "Competitive procurement for 10-100+ hour multi-day energy storage pilot installations to support grid reliability during extreme weather events.",
                        "service_territory": "PG&E Electric Service Area",
                        "utility_program_type": "Innovation RFP",
                        "year": 2025,
                        "keywords": "LDES, long duration energy storage, multi-day battery, iron-air, flow battery",
                        "technologies": ["Energy Storage", "Grid Modernization & Smart Grid"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Storage & Chemical", "Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "PGE-AWD-2025-01",
                        "recipient_name": "Form Energy, Inc.",
                        "recipient_type": "company",
                        "project_title": "100-Hour Iron-Air Multi-Day Energy Storage Demonstration at PG&E Substation",
                        "award_amount": 30000000.0,
                        "year": 2025,
                        "recipient_city": "Berkeley",
                        "recipient_state": "CA",
                        "latitude": 37.8716,
                        "longitude": -122.2727,
                        "pi_name": "Mateo Jaramillo",
                        "opportunity_sol_num": "PGE-LDES-2025",
                        "technologies": ["Energy Storage"],
                        "sectors": ["Electric Grid & Utility"]
                    },
                    {
                        "external_award_id": "PGE-AWD-2024-02",
                        "recipient_name": "LineVision, Inc.",
                        "recipient_type": "company",
                        "project_title": "Non-Contact Dynamic Line Rating (DLR) Sensor Deployment for Transmission Capacity",
                        "award_amount": 4200000.0,
                        "year": 2024,
                        "recipient_city": "San Francisco",
                        "recipient_state": "CA",
                        "latitude": 37.7749,
                        "longitude": -122.4194,
                        "pi_name": "Hudson Gilmer",
                        "opportunity_sol_num": "PGE-EPIC4-2026",
                        "technologies": ["Grid Modernization & Smart Grid"],
                        "sectors": ["Electric Grid & Utility"]
                    },
                    {
                        "external_award_id": "PGE-AWD-2024-03",
                        "recipient_name": "Camus Energy",
                        "recipient_type": "company",
                        "project_title": "Grid Orchestration Platform for High-Penetration DER Feeder Visibility",
                        "award_amount": 3500000.0,
                        "year": 2024,
                        "recipient_city": "San Jose",
                        "recipient_state": "CA",
                        "latitude": 37.3382,
                        "longitude": -121.8863,
                        "pi_name": "Astrid Atkinson",
                        "opportunity_sol_num": "PGE-DIDF-2026",
                        "technologies": ["AI, Computing & Energy Cyber", "Non-Wires Solutions (NWS)"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "Southern California Edison",
                "short_name": "SCE",
                "org_type": "utility",
                "sub_type": "Investor-Owned Utility (IOU)",
                "parent_holding_company": "Edison International",
                "website": "https://www.sce.com",
                "domain": "sce.com",
                "city": "Rosemead",
                "state": "CA",
                "zip_code": "91770",
                "service_territory": "Southern California (Los Angeles Basin, Orange County, Inland Empire, Central Coast)",
                "description": "Primary electricity supply company for much of Southern California, serving approximately 15 million people in an area of 50,000 square miles.",
                "logo_domain": "sce.com",
                "founded_year": 1886,
                "programs": [
                    {
                        "name": "SCE EPIC Technology Demonstration Program",
                        "program_type": "innovation",
                        "description": "Field demonstration of advanced technologies supporting decarbonization, customer choice, wildfire mitigation, and high DER penetration.",
                        "url": "https://www.sce.com/epic",
                        "active": True,
                        "target_stage": "demonstration",
                    },
                    {
                        "name": "SCE Distribution Deferral Opportunity (DDO)",
                        "program_type": "deployment",
                        "description": "Procurement of behind-the-meter and front-of-meter clean energy assets to defer localized transmission/distribution capital investments.",
                        "url": "https://www.sce.com/ddo",
                        "active": True,
                        "target_stage": "scale-up",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "SCE-EPIC-DEMO-2026",
                        "name": "SCE EPIC Advanced Grid & DER Technology Pilot Solicitations",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "grant",
                        "total_funding": 48000000.0,
                        "max_per_award": 6000000.0,
                        "cost_share_pct": 20.0,
                        "short_description": "Field pilots for vehicle-to-grid (V2G) bidirectional charging, smart transformer sensors, and advanced microgrid islanding controls.",
                        "service_territory": "Southern California Edison Service Area",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.sce.com/epic",
                        "year": 2026,
                        "keywords": "SCE, EPIC, V2G, bidirectional EV charging, smart transformers, microgrid controls",
                        "technologies": ["EV Charging & Infrastructure", "Grid Modernization & Smart Grid", "Microgrids & Resilience"],
                        "sectors": ["Electric Grid & Utility", "Transportation"],
                        "fuels": ["Electricity"],
                        "stage": "Pilot & Demonstration",
                    },
                    {
                        "solicitation_number": "SCE-NWA-DDO-2026",
                        "name": "SCE Distribution Deferral Opportunity (NWA) RFO",
                        "solicitation_type": "RFO",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 55000000.0,
                        "max_per_award": 20000000.0,
                        "short_description": "Clean DER, BESS, and flexible load solicitations across Orange County and Inland Empire distribution circuits.",
                        "service_territory": "Orange County & Inland Empire",
                        "utility_program_type": "NWA",
                        "procurement_portal_url": "https://www.sce.com/ddo",
                        "year": 2026,
                        "keywords": "NWA, BESS, load relief, distribution deferral, smart inverters",
                        "technologies": ["Non-Wires Solutions (NWS)", "Energy Storage", "Power Electronics & Inverters"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Electricity", "Storage & Chemical"],
                        "stage": "Deployment & Infrastructure",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "SCE-AWD-2025-01",
                        "recipient_name": "Stem, Inc.",
                        "recipient_type": "company",
                        "project_title": "AI-Driven Athena Virtual Power Plant Aggregation for SCE Distribution Deferral",
                        "award_amount": 14500000.0,
                        "year": 2025,
                        "recipient_city": "San Francisco",
                        "recipient_state": "CA",
                        "latitude": 37.7749,
                        "longitude": -122.4194,
                        "pi_name": "John Carrington",
                        "opportunity_sol_num": "SCE-NWA-DDO-2026",
                        "technologies": ["Energy Storage", "AI, Computing & Energy Cyber", "Non-Wires Solutions (NWS)"],
                        "sectors": ["Electric Grid & Utility", "Commercial"]
                    },
                    {
                        "external_award_id": "SCE-AWD-2024-02",
                        "recipient_name": "Nuvve Holding Corp.",
                        "recipient_type": "company",
                        "project_title": "Bidirectional V2G School Bus Fleet Grid Support Demonstration",
                        "award_amount": 5200000.0,
                        "year": 2024,
                        "recipient_city": "San Diego",
                        "recipient_state": "CA",
                        "latitude": 32.7157,
                        "longitude": -117.1611,
                        "pi_name": "Gregory Poilasne",
                        "opportunity_sol_num": "SCE-EPIC-DEMO-2026",
                        "technologies": ["EV Charging & Infrastructure", "Electric Vehicles & Clean Transit"],
                        "sectors": ["Transportation", "Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "San Diego Gas & Electric",
                "short_name": "SDG&E",
                "org_type": "utility",
                "sub_type": "Investor-Owned Utility (IOU)",
                "parent_holding_company": "Sempra",
                "website": "https://www.sdge.com",
                "domain": "sdge.com",
                "city": "San Diego",
                "state": "CA",
                "zip_code": "92123",
                "service_territory": "San Diego County and southern Orange County",
                "description": "Regulated public utility providing energy service to 3.7 million people through 1.5 million electric meters and 900,000 natural gas meters.",
                "logo_domain": "sdge.com",
                "founded_year": 1881,
                "programs": [
                    {
                        "name": "SDG&E Community Microgrid & Resiliency Program",
                        "program_type": "innovation",
                        "description": "Development of 100% clean community microgrids (Borrego Springs, Cameron Corners, Ramona) utilizing storage and microgrid controllers.",
                        "url": "https://www.sdge.com/clean-energy/microgrids",
                        "active": True,
                        "target_stage": "demonstration",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "SDGE-MICRO-2026",
                        "name": "SDG&E Community Microgrid & Standalone Storage Innovation RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 35000000.0,
                        "max_per_award": 12000000.0,
                        "short_description": "Solicitation for long-duration microgrid energy storage, advanced black-start islanding software, and renewable microgrid integration.",
                        "service_territory": "San Diego and South Orange Counties",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.sdge.com/procurement",
                        "year": 2026,
                        "keywords": "microgrid, islanding, black start, BESS, Borrego Springs, resilience",
                        "technologies": ["Microgrids & Resilience", "Energy Storage", "Solar PV"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Electricity", "Storage & Chemical"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "SDGE-AWD-2025-01",
                        "recipient_name": "Eos Energy Enterprises",
                        "recipient_type": "company",
                        "project_title": "Zinc-Hybrid Long-Duration Battery Storage System for SDG&E Microgrid",
                        "award_amount": 11200000.0,
                        "year": 2025,
                        "recipient_city": "Edison",
                        "recipient_state": "NJ",
                        "latitude": 40.5187,
                        "longitude": -74.4121,
                        "pi_name": "Joe Mastrangelo",
                        "opportunity_sol_num": "SDGE-MICRO-2026",
                        "technologies": ["Energy Storage", "Microgrids & Resilience"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "Los Angeles Department of Water and Power",
                "short_name": "LADWP",
                "org_type": "utility",
                "sub_type": "Municipal Utility / Public Power",
                "parent_holding_company": "City of Los Angeles",
                "website": "https://www.ladwp.com",
                "domain": "ladwp.com",
                "city": "Los Angeles",
                "state": "CA",
                "zip_code": "90012",
                "service_territory": "City of Los Angeles and Owens Valley",
                "description": "The largest municipal water and power utility in the United States, providing power to 4 million residents in the city of Los Angeles.",
                "logo_domain": "ladwp.com",
                "founded_year": 1902,
                "programs": [
                    {
                        "name": "LADWP LA100 Clean Energy Innovation Program",
                        "program_type": "innovation",
                        "description": "Path to 100% renewable, carbon-free energy by 2035 through green hydrogen conversion, battery storage, transmission expansion, and virtual power plants.",
                        "url": "https://www.ladwp.com/la100",
                        "active": True,
                        "target_stage": "deployment",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "LADWP-LA100-H2-2026",
                        "name": "LADWP Scattergood Clean Hydrogen Generation Demonstration RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 120000000.0,
                        "max_per_award": 60000000.0,
                        "short_description": "Procurement of green hydrogen production, storage, and 100% hydrogen-capable turbine generation technology at the Scattergood Generating Station.",
                        "service_territory": "City of Los Angeles",
                        "utility_program_type": "Innovation RFP",
                        "procurement_portal_url": "https://www.ladwp.com/bids",
                        "year": 2026,
                        "keywords": "green hydrogen, Scattergood, hydrogen turbine, electrolyzer, LA100",
                        "technologies": ["Hydrogen & Clean Fuels", "Fuel Cells", "Grid Modernization & Smart Grid"],
                        "sectors": ["Electric Grid & Utility", "Industry & Manufacturing"],
                        "fuels": ["Hydrogen", "Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "LADWP-AWD-2025-01",
                        "recipient_name": "Mitsubishi Power Americas",
                        "recipient_type": "company",
                        "project_title": "100% Green Hydrogen Combustion Turbine Integration at Scattergood",
                        "award_amount": 55000000.0,
                        "year": 2025,
                        "recipient_city": "Lake Mary",
                        "recipient_state": "FL",
                        "latitude": 28.7589,
                        "longitude": -81.3178,
                        "pi_name": "Bill Newsom",
                        "opportunity_sol_num": "LADWP-LA100-H2-2026",
                        "technologies": ["Hydrogen & Clean Fuels"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "Sacramento Municipal Utility District",
                "short_name": "SMUD",
                "org_type": "utility",
                "sub_type": "Municipal Utility / Public Power",
                "parent_holding_company": "SMUD Board of Directors",
                "website": "https://www.smud.org",
                "domain": "smud.org",
                "city": "Sacramento",
                "state": "CA",
                "zip_code": "95817",
                "service_territory": "Sacramento County and small portions of Placer and Yolo Counties",
                "description": "Community-owned electric utility providing electricity to 1.5 million customers with an aggressive 2030 Zero Carbon Plan.",
                "logo_domain": "smud.org",
                "founded_year": 1923,
                "programs": [
                    {
                        "name": "SMUD 2030 Zero Carbon Innovation Grants",
                        "program_type": "innovation",
                        "description": "Accelerating cutting-edge cleantech commercialization, VPP pilots, and carbon management.",
                        "url": "https://www.smud.org/Clean-Energy",
                        "active": True,
                        "target_stage": "growth",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "SMUD-ZC-VPP-2026",
                        "name": "SMUD Customer Distributed Energy & VPP Pilot Solicitations",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "grant",
                        "total_funding": 25000000.0,
                        "max_per_award": 5000000.0,
                        "short_description": "Incentivizing customer-sited heat pumps, residential battery VPP aggregation, and managed EV fleet charging.",
                        "service_territory": "Sacramento County",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.smud.org/en/Business-Solutions-and-Rebates",
                        "year": 2026,
                        "keywords": "VPP, heat pumps, building electrification, EV charging, 2030 Zero Carbon",
                        "technologies": ["Heat Pumps & Building Electrification", "Energy Storage", "EV Charging & Infrastructure"],
                        "sectors": ["Residential", "Buildings", "Electric Grid & Utility"],
                        "fuels": ["Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "SMUD-AWD-2024-01",
                        "recipient_name": "OhmConnect, Inc.",
                        "recipient_type": "company",
                        "project_title": "Sacramento Community Virtual Power Plant & Automated Heat Pump Orchestration",
                        "award_amount": 4800000.0,
                        "year": 2024,
                        "recipient_city": "Oakland",
                        "recipient_state": "CA",
                        "latitude": 37.8044,
                        "longitude": -122.2712,
                        "pi_name": "Cisco DeVries",
                        "opportunity_sol_num": "SMUD-ZC-VPP-2026",
                        "technologies": ["Heat Pumps & Building Electrification", "Non-Wires Solutions (NWS)"],
                        "sectors": ["Residential", "Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "Southern California Gas",
                "short_name": "SoCalGas",
                "org_type": "utility",
                "sub_type": "Gas Utility (IOU)",
                "parent_holding_company": "Sempra",
                "website": "https://www.socalgas.com",
                "domain": "socalgas.com",
                "city": "Los Angeles",
                "state": "CA",
                "zip_code": "90013",
                "service_territory": "Central and Southern California",
                "description": "The largest natural gas distribution utility in the nation, serving 21.8 million consumers across 24,000 square miles.",
                "logo_domain": "socalgas.com",
                "founded_year": 1867,
                "programs": [
                    {
                        "name": "SoCalGas Clean Fuels & Hydrogen Innovation Program",
                        "program_type": "innovation",
                        "description": "R&D and pilot demonstration for clean hydrogen blending, Renewable Natural Gas (RNG), and carbon capture.",
                        "url": "https://www.socalgas.com/sustainability/clean-fuels",
                        "active": True,
                        "target_stage": "demonstration",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "SOCAL-H2-RNG-2026",
                        "name": "SoCalGas Clean Hydrogen Blending & RNG Demonstration RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "grant",
                        "total_funding": 30000000.0,
                        "max_per_award": 7500000.0,
                        "short_description": "Solicitation for pipeline hydrogen blending testing, methanation technologies, and dairy RNG purification pilots.",
                        "service_territory": "Southern California Gas Territory",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.socalgas.com/clean-fuels",
                        "year": 2026,
                        "keywords": "hydrogen blending, RNG, renewable natural gas, methanation, clean fuels",
                        "technologies": ["Hydrogen & Clean Fuels", "Bioenergy & Biogas"],
                        "sectors": ["Industry & Manufacturing", "Electric Grid & Utility"],
                        "fuels": ["Hydrogen", "Biomass & Biogas"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "SOCAL-AWD-2025-01",
                        "recipient_name": "GTI Energy",
                        "recipient_type": "nonprofit",
                        "project_title": "Field Testing of 20% Hydrogen Blending in Natural Gas Distribution Networks",
                        "award_amount": 6200000.0,
                        "year": 2025,
                        "recipient_city": "Des Plaines",
                        "recipient_state": "IL",
                        "latitude": 42.0334,
                        "longitude": -87.8834,
                        "pi_name": "Paula Gant",
                        "opportunity_sol_num": "SOCAL-H2-RNG-2026",
                        "technologies": ["Hydrogen & Clean Fuels"],
                        "sectors": ["Industry & Manufacturing"]
                    }
                ]
            }
        ]
    },
    "TX": {
        "state_code": "TX",
        "state_name": "Texas",
        "gdp_billions": 2560,
        "rank": 2,
        "regulatory_body": "Public Utility Commission of Texas (PUCT) / ERCOT",
        "utilities": [
            {
                "name": "Oncor Electric Delivery",
                "short_name": "Oncor",
                "org_type": "utility",
                "sub_type": "Transmission & Distribution Utility (IOU)",
                "parent_holding_company": "Sempra",
                "website": "https://www.oncor.com",
                "domain": "oncor.com",
                "city": "Dallas",
                "state": "TX",
                "zip_code": "75201",
                "service_territory": "North, Central, and West Texas (Dallas-Fort Worth, Midland-Odessa, Waco, Tyler)",
                "description": "Texas's largest electric transmission and distribution utility, serving over 13 million Texans across 400+ communities and 98 counties.",
                "logo_domain": "oncor.com",
                "founded_year": 1912,
                "programs": [
                    {
                        "name": "Oncor Grid Resiliency & Modernization Program",
                        "program_type": "innovation",
                        "description": "Grid-enhancing technologies (GETs), microgrid integration, dynamic line rating (DLR), and advanced distribution management systems (ADMS).",
                        "url": "https://www.oncor.com/grid-modernization",
                        "active": True,
                        "target_stage": "deployment",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "ONCOR-GET-2026",
                        "name": "Oncor Grid-Enhancing Technologies (GETs) & Dynamic Line Rating RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 40000000.0,
                        "max_per_award": 10000000.0,
                        "short_description": "Procurement of sensor-based dynamic line rating (DLR), advanced power flow controllers, and ambient adjusted rating systems across ERCOT congested corridors.",
                        "service_territory": "North and West Texas ERCOT Corridors",
                        "utility_program_type": "Innovation RFP",
                        "procurement_portal_url": "https://www.oncor.com/suppliers",
                        "year": 2026,
                        "keywords": "GETs, DLR, dynamic line rating, power flow control, transmission congestion, ERCOT",
                        "technologies": ["Grid Modernization & Smart Grid", "Power Electronics & Inverters"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "ONCOR-AWD-2025-01",
                        "recipient_name": "Smart Wires Inc.",
                        "recipient_type": "company",
                        "project_title": "SmartValve Modular Power Flow Control Deployment on Oncor 138kV Transmission",
                        "award_amount": 8500000.0,
                        "year": 2025,
                        "recipient_city": "Durham",
                        "recipient_state": "NC",
                        "latitude": 35.9940,
                        "longitude": -78.8986,
                        "pi_name": "Peter Wells",
                        "opportunity_sol_num": "ONCOR-GET-2026",
                        "technologies": ["Grid Modernization & Smart Grid", "Power Electronics & Inverters"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "CenterPoint Energy Houston Electric",
                "short_name": "CenterPoint Texas",
                "org_type": "utility",
                "sub_type": "Transmission & Distribution Utility (IOU)",
                "parent_holding_company": "CenterPoint Energy",
                "website": "https://www.centerpointenergy.com",
                "domain": "centerpointenergy.com",
                "city": "Houston",
                "state": "TX",
                "zip_code": "77002",
                "service_territory": "Greater Houston Metropolitan Area (Gulf Coast)",
                "description": "Electric transmission and distribution utility serving 2.6 million customers in the Houston metropolitan area.",
                "logo_domain": "centerpointenergy.com",
                "founded_year": 1882,
                "programs": [
                    {
                        "name": "CenterPoint Resilient Grid & Microgrid Program",
                        "program_type": "deployment",
                        "description": "Comprehensive grid resiliency, smart automated reclosers, flood-hardened substations, and mobile emergency microgrids.",
                        "url": "https://www.centerpointenergy.com/resilience",
                        "active": True,
                        "target_stage": "scale-up",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "CNP-RESIL-2026",
                        "name": "CenterPoint Energy Coastal Resiliency & Mobile Microgrid RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 50000000.0,
                        "max_per_award": 15000000.0,
                        "short_description": "Procurement of containerized mobile battery microgrids and rapid-deployable clean backup generation for critical infrastructure.",
                        "service_territory": "Houston Metro / Gulf Coast",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.centerpointenergy.com/procurement",
                        "year": 2026,
                        "keywords": "microgrid, hurricane resilience, mobile battery storage, flood hardening, Houston",
                        "technologies": ["Microgrids & Resilience", "Energy Storage"],
                        "sectors": ["Electric Grid & Utility", "Government & Municipal"],
                        "fuels": ["Electricity", "Storage & Chemical"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "CNP-AWD-2025-01",
                        "recipient_name": "Enchanted Rock, LLC",
                        "recipient_type": "company",
                        "project_title": "Dual-Fuel and Clean Resilient Microgrid Deployment for Emergency Response Hubs",
                        "award_amount": 12000000.0,
                        "year": 2025,
                        "recipient_city": "Houston",
                        "recipient_state": "TX",
                        "latitude": 29.7604,
                        "longitude": -95.3698,
                        "pi_name": "Thomas McAndrew",
                        "opportunity_sol_num": "CNP-RESIL-2026",
                        "technologies": ["Microgrids & Resilience"],
                        "sectors": ["Electric Grid & Utility", "Government & Municipal"]
                    }
                ]
            },
            {
                "name": "CPS Energy",
                "short_name": "CPS Energy",
                "org_type": "utility",
                "sub_type": "Municipal Utility / Public Power",
                "parent_holding_company": "City of San Antonio",
                "website": "https://www.cpsenergy.com",
                "domain": "cpsenergy.com",
                "city": "San Antonio",
                "state": "TX",
                "zip_code": "78205",
                "service_territory": "Greater San Antonio and Bexar County",
                "description": "The nation's largest municipally owned natural gas and electric company, providing service to 900,000 electric and 375,000 natural gas customers.",
                "logo_domain": "cpsenergy.com",
                "founded_year": 1860,
                "programs": [
                    {
                        "name": "CPS Energy Flexible Path & Innovation Program",
                        "program_type": "innovation",
                        "description": "Strategic transition to clean energy via the Flexible Path, funding utility-scale battery storage, solar aggregation, and smart grid automation.",
                        "url": "https://www.cpsenergy.com/flexiblepath",
                        "active": True,
                        "target_stage": "deployment",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "CPS-FLEX-STORAGE-2026",
                        "name": "CPS Energy Grid-Scale Storage & Fast-Response Innovation RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 60000000.0,
                        "max_per_award": 25000000.0,
                        "short_description": "Procurement of 200MW/800MWh of utility-scale energy storage and fast frequency response systems.",
                        "service_territory": "Greater San Antonio / Bexar County",
                        "utility_program_type": "Innovation RFP",
                        "procurement_portal_url": "https://www.cpsenergy.com/procurement",
                        "year": 2026,
                        "keywords": "battery storage, flexible path, BESS, fast frequency response, San Antonio",
                        "technologies": ["Energy Storage", "Grid Modernization & Smart Grid"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Storage & Chemical", "Electricity"],
                        "stage": "Deployment & Infrastructure",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "CPS-AWD-2025-01",
                        "recipient_name": "Fluence Energy, Inc.",
                        "recipient_type": "company",
                        "project_title": "100MW/400MWh Gridstack Battery Storage System for San Antonio Reliability",
                        "award_amount": 22000000.0,
                        "year": 2025,
                        "recipient_city": "Arlington",
                        "recipient_state": "VA",
                        "latitude": 38.8799,
                        "longitude": -77.1067,
                        "pi_name": "Julian Nebreda",
                        "opportunity_sol_num": "CPS-FLEX-STORAGE-2026",
                        "technologies": ["Energy Storage"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "Austin Energy",
                "short_name": "Austin Energy",
                "org_type": "utility",
                "sub_type": "Municipal Utility / Public Power",
                "parent_holding_company": "City of Austin",
                "website": "https://austinenergy.com",
                "domain": "austinenergy.com",
                "city": "Austin",
                "state": "TX",
                "zip_code": "78701",
                "service_territory": "City of Austin and Travis/Williamson Counties",
                "description": "Public power utility serving more than 500,000 customer accounts across greater Austin with a national leadership role in renewable integration.",
                "logo_domain": "austinenergy.com",
                "founded_year": 1895,
                "programs": [
                    {
                        "name": "Austin Energy SHINES & DER Innovation Program",
                        "program_type": "innovation",
                        "description": "DOE SHINES-pioneered solar+storage microgrid controls, community energy storage, and EV360 clean transit integration.",
                        "url": "https://austinenergy.com/clean-energy",
                        "active": True,
                        "target_stage": "growth",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "AE-EV360-V2G-2026",
                        "name": "Austin Energy Fleet Electrification & Smart V2G Pilot RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "grant",
                        "total_funding": 18000000.0,
                        "max_per_award": 4000000.0,
                        "short_description": "Pilot solicitation for transit bus and municipal fleet smart managed charging, V2G bi-directional power flow, and local microgrid backup.",
                        "service_territory": "Austin Energy Service Area",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://austinenergy.com/procurement",
                        "year": 2026,
                        "keywords": "V2G, EV fleet, fleet electrification, smart charging, Austin, SHINES",
                        "technologies": ["EV Charging & Infrastructure", "Electric Vehicles & Clean Transit", "Microgrids & Resilience"],
                        "sectors": ["Transportation", "Government & Municipal", "Electric Grid & Utility"],
                        "fuels": ["Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "AE-AWD-2024-01",
                        "recipient_name": "Pecan Street Inc.",
                        "recipient_type": "nonprofit",
                        "project_title": "Mueller EcoDistrict High-Resolution EV & Residential DER Data Aggregation Platform",
                        "award_amount": 3800000.0,
                        "year": 2024,
                        "recipient_city": "Austin",
                        "recipient_state": "TX",
                        "latitude": 30.2672,
                        "longitude": -97.7431,
                        "pi_name": "Suzanne Russo",
                        "opportunity_sol_num": "AE-EV360-V2G-2026",
                        "technologies": ["EV Charging & Infrastructure", "AI, Computing & Energy Cyber"],
                        "sectors": ["Residential", "Transportation"]
                    }
                ]
            }
        ]
    },
    "NY": {
        "state_code": "NY",
        "state_name": "New York",
        "gdp_billions": 2150,
        "rank": 3,
        "regulatory_body": "New York State Public Service Commission (NY PSC) / NYSERDA / NYISO",
        "utilities": [
            {
                "name": "Con Edison",
                "short_name": "Con Edison",
                "org_type": "utility",
                "sub_type": "Investor-Owned Utility (IOU)",
                "parent_holding_company": "Consolidated Edison, Inc.",
                "website": "https://www.coned.com",
                "domain": "coned.com",
                "city": "New York",
                "state": "NY",
                "zip_code": "10003",
                "service_territory": "New York City (Manhattan, Bronx, Brooklyn, Queens, Staten Island) and Westchester County",
                "description": "Electric, gas, and steam utility serving 3.5 million electric customers and 1.1 million gas customers in New York City and Westchester County, leader in Non-Wires Solutions (NWS).",
                "logo_domain": "coned.com",
                "founded_year": 1823,
                "programs": [
                    {
                        "name": "Con Edison Non-Wires & Clean Innovation Program",
                        "program_type": "deployment",
                        "description": "Brooklyn Queens Demand Management (BQDM), Water Street NWS, Dynamic Load Management (DLM), and bulk battery storage RFPs.",
                        "url": "https://www.coned.com/en/business-partners/business-opportunities",
                        "active": True,
                        "target_stage": "deployment",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "CONED-NWA-2026",
                        "name": "Con Edison Non-Wires Solutions (NWS) Solicitations",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 50000000.0,
                        "max_per_award": 15000000.0,
                        "short_description": "Competitive procurement of front-of-meter battery storage, building electrification, and commercial demand response to defer transmission/substation capital projects in NYC and Westchester.",
                        "service_territory": "New York City & Westchester County",
                        "utility_program_type": "NWA",
                        "procurement_portal_url": "https://www.coned.com/en/business-partners/business-opportunities",
                        "year": 2026,
                        "keywords": "NWA, BQDM, non-wires solutions, battery storage, demand management, Con Edison, NYC",
                        "technologies": ["Non-Wires Solutions (NWS)", "Energy Storage", "Building Envelope & Efficiency"],
                        "sectors": ["Electric Grid & Utility", "Buildings", "Commercial"],
                        "fuels": ["Electricity", "Storage & Chemical"],
                        "stage": "Deployment & Infrastructure",
                    },
                    {
                        "solicitation_number": "CONED-BESS-2026",
                        "name": "Con Edison Bulk Energy Storage & Substation Peaking RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 65000000.0,
                        "max_per_award": 25000000.0,
                        "short_description": "Procurement of 200MW+ bulk energy storage systems and fast-responding grid support assets across NYC network areas.",
                        "service_territory": "New York City 5 Boroughs",
                        "utility_program_type": "Innovation RFP",
                        "procurement_portal_url": "https://www.coned.com/en/business-partners/business-opportunities",
                        "year": 2026,
                        "keywords": "bulk energy storage, BESS, peaker replacement, Con Edison, Astoria, Brooklyn",
                        "technologies": ["Energy Storage", "Grid Modernization & Smart Grid"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Storage & Chemical", "Electricity"],
                        "stage": "Deployment & Infrastructure",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "CONED-AWD-2025-01",
                        "recipient_name": "174 Power Global",
                        "recipient_type": "company",
                        "project_title": "East River 100MW/400MWh Astoria Battery Energy Storage Facility",
                        "award_amount": 22000000.0,
                        "year": 2025,
                        "recipient_city": "New York",
                        "recipient_state": "NY",
                        "latitude": 40.7128,
                        "longitude": -74.0060,
                        "pi_name": "Henry Yun",
                        "opportunity_sol_num": "CONED-BESS-2026",
                        "technologies": ["Energy Storage"],
                        "sectors": ["Electric Grid & Utility"]
                    },
                    {
                        "external_award_id": "CONED-AWD-2024-02",
                        "recipient_name": "Zinc8 Energy Solutions",
                        "recipient_type": "company",
                        "project_title": "Zinc-Air Long-Duration Battery Storage Commercial Pilot for NYC Real Estate Support",
                        "award_amount": 4500000.0,
                        "year": 2024,
                        "recipient_city": "New York",
                        "recipient_state": "NY",
                        "latitude": 40.7128,
                        "longitude": -74.0060,
                        "pi_name": "Ron MacDonald",
                        "opportunity_sol_num": "CONED-NWA-2026",
                        "technologies": ["Energy Storage", "Non-Wires Solutions (NWS)"],
                        "sectors": ["Commercial", "Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "New York Power Authority",
                "short_name": "NYPA",
                "org_type": "utility",
                "sub_type": "State Public Power Authority",
                "parent_holding_company": "State of New York",
                "website": "https://www.nypa.gov",
                "domain": "nypa.gov",
                "city": "White Plains",
                "state": "NY",
                "zip_code": "10601",
                "service_territory": "Statewide New York (generating 25%+ of NY electricity, operating 1,400+ circuit-miles of high-voltage transmission)",
                "description": "The nation's largest state public power organization, operating 16 generating facilities including Niagara and St. Lawrence-FDR Hydroelectric projects and the AGILe Innovation Lab.",
                "logo_domain": "nypa.gov",
                "founded_year": 1931,
                "programs": [
                    {
                        "name": "NYPA Clean Energy Technology & Demonstration Program (AGILe)",
                        "program_type": "innovation",
                        "description": "Advanced Grid Innovation Laboratory for Energy (AGILe) testbed, EVolve NY fast charging network, VISION2030, and high-voltage transmission innovation.",
                        "url": "https://www.nypa.gov/innovation",
                        "active": True,
                        "target_stage": "demonstration",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "NYPA-AGILE-2026",
                        "name": "NYPA AGILe Innovation Testbed & Smart Transmission RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 35000000.0,
                        "max_per_award": 10000000.0,
                        "short_description": "Procurement of real-time digital simulator (RTDS) models, digital twin substations, sensor-based dynamic line rating, and high-temperature superconducting cable technology.",
                        "service_territory": "Statewide NY Transmission System",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.nypa.gov/procurement",
                        "year": 2026,
                        "keywords": "AGILe, digital twin, RTDS, dynamic line rating, smart transmission, NYPA, White Plains",
                        "technologies": ["Grid Modernization & Smart Grid", "Power Electronics & Inverters", "AI, Computing & Energy Cyber"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "NYPA-AWD-2025-01",
                        "recipient_name": "LineVision, Inc.",
                        "recipient_type": "company",
                        "project_title": "Non-Contact Overhead Dynamic Line Rating Sensor System for Smart Path Moses-Adirondack Transmission",
                        "award_amount": 6800000.0,
                        "year": 2025,
                        "recipient_city": "Albany",
                        "recipient_state": "NY",
                        "latitude": 42.6526,
                        "longitude": -73.7562,
                        "pi_name": "Hudson Gilmer",
                        "opportunity_sol_num": "NYPA-AGILE-2026",
                        "technologies": ["Grid Modernization & Smart Grid"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "Long Island Power Authority",
                "short_name": "LIPA",
                "org_type": "utility",
                "sub_type": "Municipal Public Power Authority",
                "parent_holding_company": "LIPA Board of Trustees / PSEG Long Island",
                "website": "https://www.lipower.org",
                "domain": "lipower.org",
                "city": "Uniondale",
                "state": "NY",
                "zip_code": "11556",
                "service_territory": "Nassau and Suffolk counties on Long Island, and the Rockaways in Queens",
                "description": "Public power authority owning the electric transmission and distribution system serving 1.2 million customers on Long Island and the Rockaways.",
                "logo_domain": "lipower.org",
                "founded_year": 1985,
                "programs": [
                    {
                        "name": "LIPA Clean Energy & Resource Procurement Program",
                        "program_type": "deployment",
                        "description": "Offshore wind interconnection (South Fork Wind, Sunrise Wind), bulk battery storage RFPs, and Utility 2.0 modernization.",
                        "url": "https://www.lipower.org/clean-energy/",
                        "active": True,
                        "target_stage": "scale-up",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "LIPA-OFFSHORE-2026",
                        "name": "LIPA Offshore Wind Substation Integration & Storage RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 45000000.0,
                        "max_per_award": 15000000.0,
                        "short_description": "Procurement of high-capacity battery storage systems and harmonic filter substations for offshore wind landing points on Long Island.",
                        "service_territory": "Long Island / Nassau & Suffolk Counties",
                        "utility_program_type": "Innovation RFP",
                        "procurement_portal_url": "https://www.lipower.org/procurement",
                        "year": 2026,
                        "keywords": "offshore wind, South Fork, Sunrise Wind, BESS, LIPA, PSEG Long Island, Uniondale",
                        "technologies": ["Offshore Wind", "Energy Storage", "Grid Modernization & Smart Grid"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Wind", "Storage & Chemical", "Electricity"],
                        "stage": "Deployment & Infrastructure",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "LIPA-AWD-2024-01",
                        "recipient_name": "Key Capture Energy",
                        "recipient_type": "company",
                        "project_title": "East Hampton 20MW/80MWh Standalone Battery Storage Installation for Grid Reliability",
                        "award_amount": 12500000.0,
                        "year": 2024,
                        "recipient_city": "Albany",
                        "recipient_state": "NY",
                        "latitude": 42.6526,
                        "longitude": -73.7562,
                        "pi_name": "Jeff Bishop",
                        "opportunity_sol_num": "LIPA-OFFSHORE-2026",
                        "technologies": ["Energy Storage"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            }
        ]
    },
    "FL": {
        "state_code": "FL",
        "state_name": "Florida",
        "gdp_billions": 1580,
        "rank": 4,
        "regulatory_body": "Florida Public Service Commission (FL PSC)",
        "utilities": [
            {
                "name": "Florida Power & Light",
                "short_name": "FPL",
                "org_type": "utility",
                "sub_type": "Investor-Owned Utility (IOU)",
                "parent_holding_company": "NextEra Energy",
                "website": "https://www.fpl.com",
                "domain": "fpl.com",
                "city": "Juno Beach",
                "state": "FL",
                "zip_code": "33408",
                "service_territory": "East Coast, South Florida, and Northwest Florida (Panhandle)",
                "description": "The largest electric utility in the United States, serving over 12 million people across Florida with industry-leading solar and battery storage deployment.",
                "logo_domain": "fpl.com",
                "founded_year": 1925,
                "programs": [
                    {
                        "name": "FPL Real 30-by-30 Clean Innovation & Hydrogen Program",
                        "program_type": "innovation",
                        "description": "Massive solar, world's largest solar-powered battery storage (Manatee Energy Storage Center), and green hydrogen pilot generation (Cavendish NextGen Hydrogen Hub).",
                        "url": "https://www.fpl.com/clean-energy.html",
                        "active": True,
                        "target_stage": "deployment",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "FPL-H2-SOLAR-2026",
                        "name": "FPL Green Hydrogen & Advanced Solar-Storage Integration RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 75000000.0,
                        "max_per_award": 30000000.0,
                        "short_description": "Procurement of electrolyzers, hydrogen blending systems, and ultra-large battery storage controls supporting the Cavendish NextGen Hydrogen Hub.",
                        "service_territory": "FPL Statewide Florida Service Territory",
                        "utility_program_type": "Innovation RFP",
                        "procurement_portal_url": "https://www.fpl.com/procurement",
                        "year": 2026,
                        "keywords": "green hydrogen, Cavendish, Manatee battery, solar-plus-storage, NextEra, FPL",
                        "technologies": ["Hydrogen & Clean Fuels", "Energy Storage", "Solar PV"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Hydrogen", "Solar", "Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "FPL-AWD-2025-01",
                        "recipient_name": "Plug Power Inc.",
                        "recipient_type": "company",
                        "project_title": "PEM Electrolyzer System for Solar-Powered Green Hydrogen Generation at Okeechobee",
                        "award_amount": 28000000.0,
                        "year": 2025,
                        "recipient_city": "Latham",
                        "recipient_state": "NY",
                        "latitude": 42.7467,
                        "longitude": -73.7548,
                        "pi_name": "Andy Marsh",
                        "opportunity_sol_num": "FPL-H2-SOLAR-2026",
                        "technologies": ["Hydrogen & Clean Fuels"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "Duke Energy Florida",
                "short_name": "Duke Florida",
                "org_type": "utility",
                "sub_type": "Investor-Owned Utility (IOU)",
                "parent_holding_company": "Duke Energy",
                "website": "https://www.duke-energy.com",
                "domain": "duke-energy.com",
                "city": "St. Petersburg",
                "state": "FL",
                "zip_code": "33701",
                "service_territory": "Central Florida, Tampa Bay (Pinellas), and Northern Florida",
                "description": "Electric utility providing service to 1.9 million residential, commercial, and industrial customers across a 13,000-square-mile service area in Florida.",
                "logo_domain": "duke-energy.com",
                "founded_year": 1899,
                "programs": [
                    {
                        "name": "Duke Energy Florida Clean Energy Connection & Storage Pilots",
                        "program_type": "deployment",
                        "description": "Grid-scale battery pilot installations (Trenton, Cape San Blas, Lake Mary) and community solar aggregation.",
                        "url": "https://www.duke-energy.com/home/products/clean-energy-connection",
                        "active": True,
                        "target_stage": "scale-up",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "DEF-BESS-GRID-2026",
                        "name": "Duke Energy Florida Grid Resiliency Battery Storage RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "contract",
                        "total_funding": 45000000.0,
                        "max_per_award": 15000000.0,
                        "short_description": "Procurement of distribution-connected battery energy storage systems (BESS) for hurricane resilience and peak shaving.",
                        "service_territory": "Pinellas, Orange, and Volusia Counties",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.duke-energy.com/partner-with-us/suppliers",
                        "year": 2026,
                        "keywords": "battery storage, BESS, hurricane resilience, distribution deferral, Duke Florida",
                        "technologies": ["Energy Storage", "Microgrids & Resilience", "Grid Modernization & Smart Grid"],
                        "sectors": ["Electric Grid & Utility"],
                        "fuels": ["Storage & Chemical", "Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "DEF-AWD-2024-01",
                        "recipient_name": "Tesla Energy Operations",
                        "recipient_type": "company",
                        "project_title": "Megapack Battery Energy Storage System for Cape San Blas Grid Islanding",
                        "award_amount": 13500000.0,
                        "year": 2024,
                        "recipient_city": "Austin",
                        "recipient_state": "TX",
                        "latitude": 30.2672,
                        "longitude": -97.7431,
                        "pi_name": "Drew Baglino",
                        "opportunity_sol_num": "DEF-BESS-GRID-2026",
                        "technologies": ["Energy Storage", "Microgrids & Resilience"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            },
            {
                "name": "Orlando Utilities Commission",
                "short_name": "OUC",
                "org_type": "utility",
                "sub_type": "Municipal Utility / Public Power",
                "parent_holding_company": "City of Orlando",
                "website": "https://www.ouc.com",
                "domain": "ouc.com",
                "city": "Orlando",
                "state": "FL",
                "zip_code": "32801",
                "service_territory": "Orlando, St. Cloud, and portions of Orange and Osceola Counties",
                "description": "Known as 'The Reliable One', OUC provides electric and water service to approximately 260,000 customers in Central Florida.",
                "logo_domain": "ouc.com",
                "founded_year": 1923,
                "programs": [
                    {
                        "name": "OUC Nanogrid & Clean Hydrogen Research Center",
                        "program_type": "innovation",
                        "description": "DOE-partnered hydrogen production, fuel cell testing, and microgrid research at the Gardenia Innovation Center.",
                        "url": "https://www.ouc.com/cleanenergy",
                        "active": True,
                        "target_stage": "demonstration",
                    }
                ],
                "opportunities": [
                    {
                        "solicitation_number": "OUC-NANO-H2-2026",
                        "name": "OUC Hydrogen Microgrid & Solar-Hydrogen Nanogrid Demonstration RFP",
                        "solicitation_type": "RFP",
                        "status": "open",
                        "funding_type": "grant",
                        "total_funding": 15000000.0,
                        "max_per_award": 5000000.0,
                        "short_description": "Demonstration of solar-driven hydrogen production, storage, and stationary fuel cell power generation for emergency response centers.",
                        "service_territory": "Orlando / Orange County",
                        "utility_program_type": "Pilot / Demonstration",
                        "procurement_portal_url": "https://www.ouc.com/procurement",
                        "year": 2026,
                        "keywords": "hydrogen, fuel cell, nanogrid, microgrid, solar-to-hydrogen, OUC",
                        "technologies": ["Hydrogen & Clean Fuels", "Fuel Cells", "Microgrids & Resilience", "Solar PV"],
                        "sectors": ["Electric Grid & Utility", "Government & Municipal"],
                        "fuels": ["Hydrogen", "Solar", "Electricity"],
                        "stage": "Pilot & Demonstration",
                    }
                ],
                "awards": [
                    {
                        "external_award_id": "OUC-AWD-2024-01",
                        "recipient_name": "University of Central Florida (UCF FSEC)",
                        "recipient_type": "university",
                        "project_title": "Solar-Hydrogen Nanogrid Demonstration and Fuel Cell System Optimization",
                        "award_amount": 4200000.0,
                        "year": 2024,
                        "recipient_city": "Cocoa",
                        "recipient_state": "FL",
                        "latitude": 28.3861,
                        "longitude": -80.7431,
                        "pi_name": "Dr. James Fenton",
                        "opportunity_sol_num": "OUC-NANO-H2-2026",
                        "technologies": ["Hydrogen & Clean Fuels", "Fuel Cells"],
                        "sectors": ["Electric Grid & Utility"]
                    }
                ]
            }
        ]
    }
}
